"""Build the full course website from a repo of source files.

Repo layout::

    course.yml
    source/ps03/ps03.tex   (+ images alongside)
    source/ps04/ps04.tex
    ...

Output (default ``site/``)::

    index.html                      course home, lists all assignments
    ps/3/index.html                 handout (HTML)
    ps/3/problem-set-3.pdf          handout (PDF)
    ps/3/problem-set-3-submission.tex
    ps/3/solutions.html             ┐ only when the assignment's
    ps/3/problem-set-3-solutions.pdf┘ solutions are released

Release control comes from the ``solutions`` metadata key: an ISO date
(released once today >= date), ``released``, or ``manual`` (default: not
released).
"""

from __future__ import annotations

import html as html_mod
import re
import shutil
from dataclasses import dataclass, field
from datetime import date
from pathlib import Path
from typing import Dict, List, Optional

from .build import (
    BuildError,
    BuildResult,
    build_html,
    compile_variant_pdf,
    make_variants,
    require_course_fields,
)
import json

from .courseconfig import load_course_config
from .htmltemplate import (
    CSS,
    FOOTER_HTML,
    NAV_CSS,
    THEME_HEAD_SCRIPT,
    THEME_TOGGLE_HTML,
    THEME_TOGGLE_JS,
    file_box,
    katex_block,
    view_box,
)
from .katexmacros import extract_macros
from .metadata import Metadata, MetadataError, parse_metadata
from . import texscan

SITE_MARKER = ".hwgenie-site"


def is_released(release: Optional[str], today: Optional[date] = None) -> Optional[bool]:
    """True/False, or None for 'unparseable' (treated as not released)."""
    if not release:
        return False
    r = release.strip().lower()
    if r in ("released", "true", "yes"):
        return True
    if r in ("manual", "no", "false"):
        return False
    try:
        return date.fromisoformat(release.strip()) <= (today or date.today())
    except ValueError:
        return None


@dataclass
class AssignmentBuild:
    meta: Metadata
    source_path: Path
    rel_url: str                 # e.g. "ps/3/"
    released: bool
    files: Dict[str, Path] = field(default_factory=dict)


@dataclass
class SiteResult:
    out_dir: Path
    assignments: List[AssignmentBuild] = field(default_factory=list)
    warnings: List[str] = field(default_factory=list)
    errors: List[str] = field(default_factory=list)

    @property
    def ok(self) -> bool:
        return not self.errors


def discover_sources(source_root: Path) -> List[Path]:
    out = []
    for p in sorted(source_root.rglob("*.tex")):
        name = p.name.lower()
        if name.startswith("_") or "[submission]" in name or "[template]" in name:
            continue
        out.append(p)
    return out


def _slug(number: str) -> str:
    return re.sub(r"[^A-Za-z0-9.-]+", "-", number.strip()).strip("-").lower()


def _file_names(meta: Metadata, n: str) -> Dict[str, str]:
    """Descriptive download names, e.g. PS1-Math261-Fall2025.pdf"""
    tag = re.sub(r"\s+", "", f"{meta.course}") + "-" + re.sub(
        r"\s+", "", f"{meta.semester}"
    )
    return {
        "handout_pdf": f"PS{n}-{tag}.pdf",
        "submission": f"PS{n}-submission-{tag}.tex",
        "solutions_pdf": f"PS{n}-solutions-{tag}.pdf",
    }


def _clean_out_dir(out_dir: Path) -> None:
    if out_dir.exists():
        if any(out_dir.iterdir()) and not (out_dir / SITE_MARKER).exists():
            raise BuildError(
                f"Refusing to clean {out_dir}: it is not empty and was not "
                f"generated by hwgenie (missing {SITE_MARKER})."
            )
        shutil.rmtree(out_dir)
    out_dir.mkdir(parents=True)
    (out_dir / SITE_MARKER).write_text("generated by hwgenie\n")
    (out_dir / ".nojekyll").write_text("")


def build_site(
    repo_root: Path,
    out_dir: Optional[Path] = None,
    compile_pdfs: bool = True,
    today: Optional[date] = None,
) -> SiteResult:
    repo_root = Path(repo_root).resolve()
    cfg_path = repo_root / "course.yml"
    cfg = load_course_config(cfg_path) if cfg_path.exists() else {}
    source_root = repo_root / "source"
    if not source_root.is_dir():
        raise BuildError(f"No source/ directory found in {repo_root}")

    out = Path(out_dir) if out_dir is not None else repo_root / "site"
    result = SiteResult(out_dir=out)
    if not cfg:
        result.warnings.append("No course.yml found (or empty) in repo root.")
    _clean_out_dir(out)

    macro_pool: Dict[str, str] = {}
    for src in discover_sources(source_root):
        try:
            _build_assignment(src, cfg, out, compile_pdfs, today, result, macro_pool)
        except (BuildError, MetadataError) as e:
            result.errors.append(f"{src.relative_to(repo_root)}: {e}")

    result.assignments.sort(key=_sort_key)
    index = render_index(cfg, result.assignments, macro_pool)
    (out / "index.html").write_text(index, encoding="utf-8")
    return result


def _sort_key(a: AssignmentBuild):
    try:
        return (0, float(a.meta.number))
    except ValueError:
        return (1, a.meta.number)


def _build_assignment(
    src: Path,
    cfg: Dict[str, str],
    out: Path,
    compile_pdfs: bool,
    today: Optional[date],
    result: SiteResult,
    macro_pool: Optional[Dict[str, str]] = None,
) -> None:
    text = src.read_text(encoding="utf-8")
    if macro_pool is not None:
        macro_pool.update(extract_macros(text))
    meta = parse_metadata(texscan.mask_verbatim(text))
    meta.course = meta.course or cfg.get("course")
    meta.semester = meta.semester or cfg.get("semester")
    require_course_fields(meta)
    if meta.doc_type != "problemset":
        result.warnings.append(
            f"{src.name}: type {meta.doc_type!r} not supported yet; skipped."
        )
        return

    released = is_released(meta.solutions_release, today)
    if released is None:
        result.warnings.append(
            f"{src.name}: could not parse solutions = "
            f"{meta.solutions_release!r} (expected a YYYY-MM-DD date, "
            "'manual', or 'released'); treating as NOT released."
        )
        released = False

    n = _slug(meta.number)
    ps_dir = out / "ps" / n
    ps_dir.mkdir(parents=True, exist_ok=True)
    ab = AssignmentBuild(
        meta=meta, source_path=src, rel_url=f"ps/{n}/", released=released
    )
    variants = make_variants(text)
    names = _file_names(meta, n)

    # Submission template (.tex)
    submission_path = ps_dir / names["submission"]
    submission_path.write_text(variants["submission"], encoding="utf-8")
    ab.files["submission"] = submission_path

    # A per-assignment BuildResult to collect html warnings.
    br = BuildResult(meta=meta, out_dir=ps_dir)

    course_name = cfg.get("course", "Course home")
    home = f'<a href="../../">← {html_mod.escape(course_name)}</a>'
    sb_home = ("../../", course_name)
    boxes = [
        file_box(names["handout_pdf"], "Problem Set PDF"),
        file_box(names["submission"], "LaTeX source"),
    ]
    if released:
        boxes.append(file_box(names["solutions_pdf"], "Solutions PDF"))

    handout_nav = [home]
    if released:
        handout_nav.append(view_box("solutions.html", "Solutions"))
    handout_nav += boxes
    build_html(
        variants["handout"], meta, False, ps_dir / "index.html",
        src.parent, br, nav=" ".join(handout_nav), sb_home=sb_home,
    )
    ab.files["handout_html"] = ps_dir / "index.html"

    if released:
        sol_nav = [home, view_box("./", "Problem Set")] + boxes
        build_html(
            variants["solutions_web"], meta, True, ps_dir / "solutions.html",
            src.parent, br, nav=" ".join(sol_nav), sb_home=sb_home,
        )
        ab.files["solutions_html"] = ps_dir / "solutions.html"

    if compile_pdfs:
        pdf_path, error = compile_variant_pdf(
            variants["handout"], ps_dir, src.parent,
            names["handout_pdf"], "_hwg_handout",
        )
        if pdf_path:
            ab.files["handout_pdf"] = pdf_path
        if error:
            result.errors.append(f"{src.name}: {error}")
        if released:
            pdf_path, error = compile_variant_pdf(
                variants["solutions"], ps_dir, src.parent,
                names["solutions_pdf"], "_hwg_solutions",
            )
            if pdf_path:
                ab.files["solutions_pdf"] = pdf_path
            if error:
                result.errors.append(f"{src.name}: {error}")

    result.warnings.extend(f"{src.name}: {w}" for w in br.warnings)
    result.assignments.append(ab)


# ------------------------------------------------------------------ index page

INDEX_CSS = """
.assignment {
  background: var(--card-bg);
  padding: 1.05rem 1.3rem;
  margin: 1.1rem 0;
}
.assignment h2 {
  font-size: 1.1rem;
  margin: 0 0 .35rem;
}
.assignment h2 a { color: var(--fg); text-decoration: none; }
.assignment h2 a:hover { color: var(--accent); }
.assignment .links {
  font-family: system-ui, -apple-system, "Segoe UI", sans-serif;
  font-size: .85rem;
  display: flex;
  flex-wrap: wrap;
  gap: .3rem .6rem;
}
.assignment .links a { color: var(--accent); text-decoration: none; }
.assignment .links a:hover { text-decoration: underline; }
.assignment .links .sep-dot, .assignment .links .pending { color: var(--muted); }
"""


def render_index(
    cfg: Dict[str, str],
    assignments: List[AssignmentBuild],
    macros: Optional[Dict[str, str]] = None,
) -> str:
    e = html_mod.escape
    course = cfg.get("course", "Course")
    title = cfg.get("title")
    semester = cfg.get("semester", "")
    instructor = cfg.get("instructor")
    heading = f"{course}: {title}" if title else course
    sub = " · ".join(x for x in (semester, instructor) if x)

    cards = []
    for a in assignments:
        n = e(a.meta.number)
        label = f"Problem Set {n}"
        if a.meta.title:
            label += f": {e(a.meta.title)}"
        slug = _slug(a.meta.number)
        names = _file_names(a.meta, slug)
        links = []
        if a.released:
            links.append(view_box(f"{a.rel_url}solutions.html", "Solutions"))
        links += [
            file_box(f'{a.rel_url}{names["handout_pdf"]}', "Problem Set PDF"),
            file_box(f'{a.rel_url}{names["submission"]}', "LaTeX source"),
        ]
        if a.released:
            links.append(
                file_box(f'{a.rel_url}{names["solutions_pdf"]}', "Solutions PDF")
            )
        cards.append(
            f'<div class="assignment">\n'
            f'<h2><a href="{a.rel_url}">{label}</a></h2>\n'
            f'<div class="links">{" ".join(links)}</div>\n</div>'
        )

    body = "\n".join(cards) if cards else "<p>No assignments posted yet.</p>"
    macros_json = json.dumps(macros or {}, ensure_ascii=False)
    plain_heading = re.sub(r"\$", "", heading)
    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{e(plain_heading)} — {e(semester)}</title>
{THEME_HEAD_SCRIPT}
{katex_block(macros_json)}
<style>{CSS}{NAV_CSS}{INDEX_CSS}</style>
</head>
<body>
{THEME_TOGGLE_HTML}
<main>
<header class="doc">
<p class="course">{e(sub)}</p>
<h1>{e(heading)}</h1>
</header>
<section>
<h2 style="font-size:1.15rem">Problem Sets</h2>
{body}
</section>
<footer class="doc">{FOOTER_HTML}</footer>
</main>
{THEME_TOGGLE_JS}
</body>
</html>
"""
