"""Build the full course website from a repo of source files.

Repo layout::

    course.yml
    source/ps03/ps03.tex   (+ images alongside)
    source/ps04/ps04.tex
    ...

Output (default ``site/``)::

    index.html                      course home, lists all assignments
    ps/3/index.html                 handout (HTML)
    ps/3/problem-set-3.pdf          handout (PDF)
    ps/3/problem-set-3-submission.tex
    ps/3/solutions.html             ┐ only when the assignment's
    ps/3/problem-set-3-solutions.pdf┘ solutions are released

Release control comes from the ``solutions`` metadata key: an ISO date
(released once today >= date), ``released``, or ``manual`` (default: not
released).
"""

from __future__ import annotations

import html as html_mod
import re
import shutil
from dataclasses import dataclass, field
from datetime import date
from pathlib import Path
from typing import Dict, List, Optional

from .build import (
    BuildError,
    BuildResult,
    build_html,
    compile_variant_pdf,
    make_variants,
    require_course_fields,
)
import json

from .courseconfig import load_course_config
from .htmltemplate import (
    CSS,
    FOOTER_HTML,
    NAV_CSS,
    SCROLLBAR_JS,
    THEME_HEAD_SCRIPT,
    THEME_TOGGLE_HTML,
    THEME_TOGGLE_JS,
    file_box,
    katex_block,
    scrollbar_html,
    view_box,
)
from .katexmacros import extract_macros
from .metadata import Metadata, MetadataError, latex_plain, parse_metadata
from .themes import theme_from_config
from . import texscan

SITE_MARKER = ".hwgenie-site"


def is_released(release: Optional[str], today: Optional[date] = None) -> Optional[bool]:
    """True/False, or None for 'unparseable' (treated as not released).

    The documented grammar is simply 'yes' / 'no'; older spellings
    (released/manual) and ISO dates keep working for compatibility.
    """
    if not release:
        return False
    r = release.strip().lower()
    if r in ("yes", "released", "true"):
        return True
    if r in ("no", "manual", "false"):
        return False
    try:
        return date.fromisoformat(release.strip()) <= (today or date.today())
    except ValueError:
        return None


@dataclass
class AssignmentBuild:
    meta: Metadata
    source_path: Path
    rel_url: str                 # e.g. "ps/3/"
    released: bool
    files: Dict[str, Path] = field(default_factory=dict)


@dataclass
class SiteResult:
    out_dir: Path
    assignments: List[AssignmentBuild] = field(default_factory=list)
    warnings: List[str] = field(default_factory=list)
    errors: List[str] = field(default_factory=list)

    @property
    def ok(self) -> bool:
        return not self.errors


def discover_sources(source_root: Path) -> List[Path]:
    out = []
    for p in sorted(source_root.rglob("*.tex")):
        rel_parts = p.relative_to(source_root).parts
        if any(part.startswith("_") for part in rel_parts):
            continue  # _experiments/ and friends stay out of the site
        name = p.name.lower()
        if "[submission]" in name or "[template]" in name:
            continue
        out.append(p)
    return out


def _slug(number: str) -> str:
    return re.sub(r"[^A-Za-z0-9.-]+", "-", number.strip()).strip("-").lower()


def _tag(meta: Metadata) -> str:
    return re.sub(r"\s+", "", f"{meta.course}") + "-" + re.sub(
        r"\s+", "", f"{meta.semester}")


def _page_pdf_name(meta: Metadata, n: str) -> str:
    if meta.doc_type == "lesson":
        return f"Lesson{n}-{_tag(meta)}.pdf"
    return f"Syllabus-{_tag(meta)}.pdf"


def _file_names(meta: Metadata, n: str) -> Dict[str, str]:
    """Descriptive download names, e.g. PS1-Math261-Fall2025.pdf"""
    tag = re.sub(r"\s+", "", f"{meta.course}") + "-" + re.sub(
        r"\s+", "", f"{meta.semester}"
    )
    return {
        "handout_pdf": f"PS{n}-{tag}.pdf",
        "submission": f"PS{n}-submission-{tag}.tex",
        "solutions_pdf": f"PS{n}-solutions-{tag}.pdf",
    }


def _find_static_asset(repo_root: Path, stem: str, exts: tuple) -> str:
    """First static/<stem>.<ext> that exists (static/ publishes at site root)."""
    for ext in exts:
        if (repo_root / "static" / f"{stem}{ext}").exists():
            return f"{stem}{ext}"
    return ""


BANNER_EXTS = (".png", ".jpg", ".jpeg", ".webp", ".svg", ".gif")
FAVICON_EXTS = (".svg", ".png", ".ico", ".gif", ".jpg", ".jpeg")


def _clean_out_dir(out_dir: Path) -> None:
    if out_dir.exists():
        if any(out_dir.iterdir()) and not (out_dir / SITE_MARKER).exists():
            raise BuildError(
                f"Refusing to clean {out_dir}: it is not empty and was not "
                f"generated by hwgenie (missing {SITE_MARKER})."
            )
        shutil.rmtree(out_dir)
    out_dir.mkdir(parents=True)
    (out_dir / SITE_MARKER).write_text("generated by hwgenie\n")
    (out_dir / ".nojekyll").write_text("")


def build_site(
    repo_root: Path,
    out_dir: Optional[Path] = None,
    compile_pdfs: bool = True,
    today: Optional[date] = None,
) -> SiteResult:
    repo_root = Path(repo_root).resolve()
    cfg_path = repo_root / "course.yml"
    cfg = load_course_config(cfg_path) if cfg_path.exists() else {}
    source_root = repo_root / "source"
    if not source_root.is_dir():
        raise BuildError(f"No source/ directory found in {repo_root}")

    out = Path(out_dir) if out_dir is not None else repo_root / "site"
    result = SiteResult(out_dir=out)
    if not cfg:
        result.warnings.append("No course.yml found (or empty) in repo root.")
    _clean_out_dir(out)

    sty_path = repo_root / "hwgenie.sty"
    extra_preamble = (
        sty_path.read_text(encoding="utf-8") if sty_path.exists() else ""
    )
    theme = theme_from_config(cfg)
    custom_css_on = (repo_root / "static" / "custom.css").exists()
    # Optional art, by conventional filename (like custom.css / intro.html):
    # static/banner.* = home-page hero; static/favicon.* = tab icon site-wide.
    banner = _find_static_asset(repo_root, "banner", BANNER_EXTS)
    favicon = _find_static_asset(repo_root, "favicon", FAVICON_EXTS)
    intro_path = repo_root / "static" / "intro.html"
    intro_html = (
        intro_path.read_text(encoding="utf-8") if intro_path.exists() else ""
    )

    # Every file in handouts/ is published at handouts/<name> and listed in
    # the index's Handouts section.
    handout_files = []
    handouts_dir = repo_root / "handouts"
    if handouts_dir.is_dir():
        (out / "handouts").mkdir(parents=True, exist_ok=True)
        for f in sorted(handouts_dir.iterdir()):
            if (f.is_file() and not f.name.startswith(".")
                    and not f.name.lower().startswith("readme")):
                shutil.copyfile(f, out / "handouts" / f.name)
                handout_files.append(f.name)

    macro_pool: Dict[str, str] = {}
    if extra_preamble:
        macro_pool.update(extract_macros(extra_preamble))
    for src in discover_sources(source_root):
        try:
            _build_assignment(
                src, cfg, out, compile_pdfs, today, result, macro_pool,
                extra_preamble=extra_preamble, theme=theme, repo_root=repo_root,
                custom_css_on=custom_css_on, favicon=favicon,
            )
        except (BuildError, MetadataError) as e:
            result.errors.append(f"{src.relative_to(repo_root)}: {e}")

    result.assignments.sort(key=_sort_key)
    index = render_index(
        cfg, result.assignments, macro_pool, theme=theme,
        custom_css="custom.css" if custom_css_on else "",
        intro_html=intro_html, handout_files=handout_files,
        banner=banner, favicon=favicon,
    )
    (out / "index.html").write_text(index, encoding="utf-8")

    # Files in static/ are published verbatim at the site root, after the
    # generated site, so they can add pages or override generated ones.
    static_dir = repo_root / "static"
    if static_dir.is_dir():
        shutil.copytree(static_dir, out, dirs_exist_ok=True)
    return result


def _sort_key(a: AssignmentBuild):
    try:
        return (0, float(a.meta.number))
    except ValueError:
        return (1, a.meta.number)


def _build_assignment(
    src: Path,
    cfg: Dict[str, str],
    out: Path,
    compile_pdfs: bool,
    today: Optional[date],
    result: SiteResult,
    macro_pool: Optional[Dict[str, str]] = None,
    extra_preamble: str = "",
    theme: str = "",
    repo_root: Optional[Path] = None,
    custom_css_on: bool = False,
    favicon: str = "",
) -> None:
    text = src.read_text(encoding="utf-8")
    if macro_pool is not None:
        macro_pool.update(extract_macros(text))
    meta = parse_metadata(texscan.mask_verbatim(text))
    meta.course = meta.course or cfg.get("course")
    meta.semester = meta.semester or cfg.get("semester")
    require_course_fields(meta)
    if meta.doc_type not in ("problemset", "lesson", "syllabus"):
        result.warnings.append(
            f"{src.name}: type {meta.doc_type!r} not supported yet; skipped."
        )
        return

    # Whole-assignment gate: \hwrelease{date|released} hides an in-progress
    # problem set from the site entirely until it is due to appear.
    if meta.release is not None:
        assignment_live = is_released(meta.release, today)
        if not assignment_live:
            result.warnings.append(
                f"{src.name}: not released yet (release = {meta.release!r}); "
                "not built into the site."
            )
            return

    if meta.doc_type in ("lesson", "syllabus"):
        _build_page_doc(
            src, cfg, out, compile_pdfs, result, meta, text,
            extra_preamble, theme, repo_root, custom_css_on, favicon,
        )
        return

    released = is_released(meta.solutions_release, today)
    if released is None:
        result.warnings.append(
            f"{src.name}: could not parse solutions = "
            f"{meta.solutions_release!r} (expected 'yes' or 'no'); "
            "treating as NOT released."
        )
        released = False

    n = _slug(meta.number)
    ps_dir = out / "ps" / n
    ps_dir.mkdir(parents=True, exist_ok=True)
    ab = AssignmentBuild(
        meta=meta, source_path=src, rel_url=f"ps/{n}/", released=released
    )
    search_dirs = [src.parent] + ([repo_root] if repo_root else [])
    variants = make_variants(text, search_dirs=search_dirs)
    names = _file_names(meta, n)

    # Submission template (.tex)
    submission_path = ps_dir / names["submission"]
    submission_path.write_text(variants["submission"], encoding="utf-8")
    ab.files["submission"] = submission_path

    # A per-assignment BuildResult to collect html warnings.
    br = BuildResult(meta=meta, out_dir=ps_dir)

    course_name = cfg.get("course", "Course home")
    # Back links land on the matching section of the course home page.
    home = view_box("../../#problem-sets", f"← {html_mod.escape(course_name)}")
    sb_home = ("../../#problem-sets", course_name)
    boxes = [
        file_box(names["handout_pdf"], "Problem Set PDF"),
        file_box(names["submission"], "LaTeX source"),
    ]
    if released:
        boxes.append(file_box(names["solutions_pdf"], "Solutions PDF"))

    handout_nav = [home]
    if released:
        handout_nav.append(view_box("solutions.html", "Solutions"))
    handout_nav += boxes
    build_html(
        variants["handout"], meta, False, ps_dir / "index.html",
        src.parent, br, nav=" ".join(handout_nav), sb_home=sb_home,
        extra_preamble=extra_preamble, theme=theme,
        image_search=[repo_root] if repo_root else None,
        custom_css="../../custom.css" if custom_css_on else "",
        favicon=f"../../{favicon}" if favicon else "",
    )
    ab.files["handout_html"] = ps_dir / "index.html"

    if released:
        sol_nav = [home, view_box("./", "Problem Set")] + boxes
        build_html(
            variants["solutions_web"], meta, True, ps_dir / "solutions.html",
            src.parent, br, nav=" ".join(sol_nav), sb_home=sb_home,
            extra_preamble=extra_preamble, theme=theme,
            image_search=[repo_root] if repo_root else None,
            custom_css="../../custom.css" if custom_css_on else "",
            favicon=f"../../{favicon}" if favicon else "",
        )
        ab.files["solutions_html"] = ps_dir / "solutions.html"

    if compile_pdfs:
        pdf_path, error = compile_variant_pdf(
            variants["handout"], ps_dir, src.parent,
            names["handout_pdf"], "_hwg_handout",
            extra_inputs=repo_root if extra_preamble else None,
        )
        if pdf_path:
            ab.files["handout_pdf"] = pdf_path
        if error:
            result.errors.append(f"{src.name}: {error}")
        if released:
            pdf_path, error = compile_variant_pdf(
                variants["solutions"], ps_dir, src.parent,
                names["solutions_pdf"], "_hwg_solutions",
                extra_inputs=repo_root if extra_preamble else None,
            )
            if pdf_path:
                ab.files["solutions_pdf"] = pdf_path
            if error:
                result.errors.append(f"{src.name}: {error}")

    result.warnings.extend(f"{src.name}: {w}" for w in br.warnings)
    result.assignments.append(ab)


def _build_page_doc(
    src: Path,
    cfg: Dict[str, str],
    out: Path,
    compile_pdfs: bool,
    result: SiteResult,
    meta: Metadata,
    text: str,
    extra_preamble: str,
    theme: str,
    repo_root: Optional[Path],
    custom_css_on: bool,
    favicon: str = "",
) -> None:
    """Lessons and the syllabus: one PDF + one HTML page, no variants."""
    from . import transforms

    search_dirs = [src.parent] + ([repo_root] if repo_root else [])
    text = transforms.expand_inputs(text, search_dirs)

    if meta.doc_type == "lesson":
        n = _slug(meta.number)
        rel_url = f"lessons/{n}/"
        page_dir = out / "lessons" / n
        depth = 2
    else:
        n = ""
        rel_url = "syllabus/"
        page_dir = out / "syllabus"
        depth = 1
    page_dir.mkdir(parents=True, exist_ok=True)
    pdf_name = _page_pdf_name(meta, n)

    ab = AssignmentBuild(meta=meta, source_path=src, rel_url=rel_url,
                         released=True)
    br = BuildResult(meta=meta, out_dir=page_dir)
    course_name = cfg.get("course", "Course home")
    # Back links land on the matching section of the course home page.
    section = "#lessons" if meta.doc_type == "lesson" else "#handouts"
    home_href = "../" * depth + section
    home = view_box(home_href, f"← {html_mod.escape(course_name)}")
    nav = " ".join([home, file_box(pdf_name, "PDF")])
    build_html(
        text, meta, True, page_dir / "index.html", src.parent, br,
        nav=nav, sb_home=(home_href, course_name),
        extra_preamble=extra_preamble, theme=theme,
        image_search=[repo_root] if repo_root else None,
        custom_css=("../" * depth + "custom.css") if custom_css_on else "",
        favicon=("../" * depth + favicon) if favicon else "",
    )
    ab.files["html"] = page_dir / "index.html"

    if compile_pdfs:
        pdf_path, error = compile_variant_pdf(
            text, page_dir, src.parent, pdf_name, "_hwg_page",
            extra_inputs=repo_root if extra_preamble else None,
        )
        if pdf_path:
            ab.files["pdf"] = pdf_path
        if error:
            result.errors.append(f"{src.name}: {error}")

    result.warnings.extend(f"{src.name}: {w}" for w in br.warnings)
    result.assignments.append(ab)


# ------------------------------------------------------------------ index page

INDEX_CSS = """
.assignment {
  background: var(--card-bg);
  padding: 1.05rem 1.3rem;
  margin: 1.1rem 0;
}
.assignment h2 {
  font-size: 1.1rem;
  margin: 0 0 .35rem;
}
.assignment h2 a { color: var(--fg); }
.assignment h2 a:hover { background: var(--hover-bg); }
.assignment .links {
  font-family: system-ui, -apple-system, "Segoe UI", sans-serif;
  font-size: .85rem;
  display: flex;
  flex-wrap: wrap;
  gap: .3rem .6rem;
}
.assignment .links .sep-dot, .assignment .links .pending { color: var(--muted); }
/* Section headers: centered, flanked by long dashes. */
h2.index-head {
  display: flex;
  align-items: center;
  justify-content: center;
  gap: .9rem;
  font-size: 1.15rem;
  margin: 2.6rem 0 1.2rem;
}
h2.index-head::before, h2.index-head::after {
  content: "";
  width: 4.5rem;
  border-top: 1px solid var(--muted);
  opacity: .6;
}
/* Optional banner art (static/banner.*): full-width hero at the top of the
   course home, with the usual title header floating in a borderless card. */
.hero {
  position: relative;
  display: flex;
  align-items: center;
  justify-content: center;
  max-width: 44rem;   /* match the text column so wide screens don't stretch it */
  margin: 0 auto;
  min-height: 11rem;  /* fixed: card-to-edge spacing must not scale with viewport */
  padding: 2.5rem 1.1rem;
}
.hero img {
  position: absolute;
  inset: 0;
  width: 100%;
  height: 100%;
  object-fit: cover;
}
.hero header.doc {
  position: relative;
  margin: 0;
  max-width: min(100%, 38rem);
  padding: 1.2rem 2rem;
  background: var(--card-bg);
}
"""


def render_index(
    cfg: Dict[str, str],
    assignments: List[AssignmentBuild],
    macros: Optional[Dict[str, str]] = None,
    theme: str = "",
    custom_css: str = "",
    intro_html: str = "",
    handout_files: Optional[List[str]] = None,
    banner: str = "",
    favicon: str = "",
) -> str:
    if not theme:
        theme = theme_from_config(cfg)
    e = html_mod.escape
    course = cfg.get("course", "Course")
    title = cfg.get("title")
    semester = cfg.get("semester", "")
    instructor = cfg.get("instructor")
    heading = f"{course}: {title}" if title else course
    sub = " · ".join(x for x in (semester, instructor) if x)

    problemsets = [a for a in assignments if a.meta.doc_type == "problemset"]
    lessons = [a for a in assignments if a.meta.doc_type == "lesson"]
    syllabi = [a for a in assignments if a.meta.doc_type == "syllabus"]

    top_cards = []
    for a in syllabi:
        pdf = _page_pdf_name(a.meta, "")
        top_cards.append(
            f'<div class="assignment">\n'
            f'<h2><a href="{a.rel_url}">Syllabus</a></h2>\n'
            f'<div class="links">'
            f'{file_box(f"{a.rel_url}{pdf}", "Syllabus PDF")}</div>\n</div>'
        )
    for fname in handout_files or []:
        pretty = re.sub(r"[-_]+", " ", fname.rsplit(".", 1)[0]).strip().title()
        top_cards.append(
            f'<div class="assignment">\n'
            f'<h2>{e(pretty)}</h2>\n'
            f'<div class="links">'
            f'{file_box(f"handouts/{fname}", e(fname))}</div>\n</div>'
        )

    lesson_cards = []
    for a in lessons:
        num = e(a.meta.number)
        label = f"Lesson {num}"
        if a.meta.title:
            label += f": {e(latex_plain(a.meta.title))}"
        slug = _slug(a.meta.number)
        pdf = _page_pdf_name(a.meta, slug)
        lesson_cards.append(
            f'<div class="assignment">\n'
            f'<h2><a href="{a.rel_url}">{label}</a></h2>\n'
            f'<div class="links">'
            f'{file_box(f"{a.rel_url}{pdf}", "Lesson PDF")}</div>\n</div>'
        )

    cards = []
    for a in problemsets:
        n = e(a.meta.number)
        label = f"Problem Set {n}"
        if a.meta.title:
            label += f": {e(latex_plain(a.meta.title))}"
        slug = _slug(a.meta.number)
        names = _file_names(a.meta, slug)
        links = []
        if a.released:
            links.append(view_box(f"{a.rel_url}solutions.html", "Solutions"))
        links += [
            file_box(f'{a.rel_url}{names["handout_pdf"]}', "Problem Set PDF"),
            file_box(f'{a.rel_url}{names["submission"]}', "LaTeX source"),
        ]
        if a.released:
            links.append(
                file_box(f'{a.rel_url}{names["solutions_pdf"]}', "Solutions PDF")
            )
        cards.append(
            f'<div class="assignment">\n'
            f'<h2><a href="{a.rel_url}">{label}</a></h2>\n'
            f'<div class="links">{" ".join(links)}</div>\n</div>'
        )

    sections = []
    if intro_html:
        sections.append(f'<div class="intro">\n{intro_html}\n</div>')
    if top_cards:
        sections.append(
            '<h2 class="index-head" id="handouts">Handouts</h2>\n'
            + "\n".join(top_cards)
        )
    if lesson_cards:
        sections.append(
            '<h2 class="index-head" id="lessons">Lessons</h2>\n'
            + "\n".join(lesson_cards)
        )
    if cards:
        sections.append(
            '<h2 class="index-head" id="problem-sets">Problem Sets</h2>\n'
            + "\n".join(cards)
        )
    body = "\n".join(sections) if sections else "<p>Nothing posted yet.</p>"
    # Sticky nav (appears on scroll, same component as assignment pages):
    # section jumps for whichever sections exist.
    jumps = []
    if top_cards:
        jumps.append(("Handouts", "handouts"))
    if lesson_cards:
        jumps.append(("Lessons", "lessons"))
    if cards:
        jumps.append(("Problem Sets", "problem-sets"))
    scrollbar = scrollbar_html(None, "", course, jumps) if jumps else ""
    macros_json = json.dumps(macros or {}, ensure_ascii=False)
    plain_heading = re.sub(r"\$", "", heading)
    header = (
        f'<header class="doc">\n'
        f'<p class="course">{e(sub)}</p>\n'
        f"<h1>{e(heading)}</h1>\n"
        f"</header>"
    )
    # With banner art the header card floats in a full-width hero instead of
    # sitting at the top of the text column.
    hero = f'<div class="hero">\n<img src="{banner}" alt="">\n{header}\n</div>'
    icon_link = f'<link rel="icon" href="{favicon}">' if favicon else ""
    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{e(plain_heading)} — {e(semester)}</title>
{icon_link}
{THEME_HEAD_SCRIPT}
{katex_block(macros_json)}
<style>{theme}{CSS}{NAV_CSS}{INDEX_CSS}</style>
{f'<link rel="stylesheet" href="{custom_css}">' if custom_css else ""}
</head>
<body id="top">
{THEME_TOGGLE_HTML}
{scrollbar}
{hero if banner else ""}
<main>
{"" if banner else header}
<section>
{body}
</section>
<footer class="doc">{FOOTER_HTML}</footer>
</main>
{THEME_TOGGLE_JS}
{SCROLLBAR_JS}
</body>
</html>
"""
